sudo: required
language: bash

dist: xenial

# safelist
branches:
  only:
  - master

services:
  - docker

script:
  # enable experimental features.
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - mkdir $HOME/.docker
  - touch $HOME/.docker/config.json
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker restart
  - docker version -f '{{.Server.Experimental}}'
  - docker version
  # build everything
  - build-amd64.sh
  #- .deploy/docker/build-arm.sh
  #- .deploy/docker/manifest.sh
