sudo: required
language: bash

dist: xenial

# safelist
branches:
  only:
  - master

services:
  - docker

jobs:
  include:
    - dist: xenial
      arch: amd64
      env: ARCH=amd64
    - dist: xenial
      arch: amd64
      env: ARCH=arm
    - dist: xenial
      arch: arm64
      env: ARCH=arm64

script:
  - ./travis.sh
